#!/bin/sh
#
# $0 ../function_defs.list OUTDIR
#
# Generates output files with various defs and lookup arrays.

infile="$1"
outdir="$2"

if [ -z "${infile}" -o ! -r "${infile}" ]; then
	echo "No infile."
	exit 1
fi

if [ -z "${outdir}" -o ! -d "${outdir}" ]; then
	echo "No outdir."
	exit 1
fi

# Stripping out commands, blank lines, etc.
CLEANDAT="-e s/#.*// -e /^[[:space:]]*$/d"

# Uppercasing
TOUPPER="tr [:lower:] [:upper:]"

# We're all C here
print_header() {
	echo "/*"
	echo " * AUTOGENERATED FILE -- DO NOT EDIT"
	echo " * This file is generated automatically by $0"
	echo " * from '${infile}'"
	echo " * during the build process."
	echo " */"
	echo
}


# First off, creating the F_ defines.
gf="${outdir}/function_defs.h"
(
	print_header
	echo "/* Definitions for functions */"
	echo
	echo "#define F_NOP 0    /* Standin */"
	echo

	counter=1

	echo "/* Standard functions */"
	sed -e '1,/^# START(main)/d' -e '/^# END(main)/,$d' \
		${CLEANDAT} ${infile} \
		| sort \
		| awk '{printf "%s %s\n" toupper($1), ($3 == "-" ? "" : $3)}' \
		| while read func ifdef
	do
		if [ ! -z "${ifdef}" ]; then
			echo "#ifdef ${ifdef}"
		fi
		printf "#define F_%-21s ${counter}\n" "${func}"
		if [ ! -z "${ifdef}" ]; then
			echo "#endif"
		fi
		counter=$((counter+1))
	done

	echo
	echo "/* Synthetic functions */"
	sed -e '1,/^# START(synthetic)/d' -e '/^# END(synthetic)/,$d' \
		${CLEANDAT} ${infile} \
		| sort \
		| awk '{printf "%s\n", toupper($1)}' \
		| while read func
	do
		printf "#define F_%-21s ${counter}\n" "${func}"
		counter=$((counter+1))
	done

) > ${gf}
echo "Generated ${gf}"
